import type { IconSource } from '@rootnative/utils'
import type { ReactNode } from 'react'
import type {
  PressableProps,
  StyleProp,
  TextStyle,
  ViewStyle,
} from 'react-native'

/** Visual variant of the chip following Material Design 3 chip types. */
export type ChipVariant = 'assist' | 'filter' | 'input' | 'suggestion'

interface ChipCommonProps extends Omit<PressableProps, 'children' | 'style'> {
  /** Text label rendered inside the chip. */
  children: string
  /**
   * Size of the leading icon in dp.
   * @default 18
   */
  iconSize?: number
  /**
   * Override the container (background) color.
   * State-layer colors (hover, press) are derived automatically.
   */
  containerColor?: string
  /**
   * Override the content (label and icon) color.
   * State-layer colors are derived automatically when no containerColor is set.
   */
  contentColor?: string
  /** Additional style applied to the label text. */
  labelStyle?: StyleProp<TextStyle>
  /**
   * Accessible label for the trailing close affordance, when one renders.
   *
   * The close button is a second target inside what looks like one control, so
   * a bare "Remove" leaves a screen-reader user with no way to tell which chip
   * they are on. Defaults to `` `Remove ${children}` `` — the chip's own label
   * composed in — which is also why this is a prop: that default is English,
   * and word order does not survive translation.
   *
   * @default `Remove ${children}`
   */
  closeAccessibilityLabel?: string
  /**
   * Style applied to the root container. Static form only — the function
   * form `(state) => style` is not supported because the component drives
   * its container background through Reanimated. Use `containerColor` /
   * `contentColor` for state-aware styling.
   */
  style?: StyleProp<ViewStyle>
}

/**
 * Assist chip — surfaces smart, contextual actions related to the surrounding
 * content. Default variant.
 */
export interface AssistChipProps extends ChipCommonProps {
  variant?: 'assist'
  /**
   * Whether the chip uses an elevated surface instead of an outline border.
   * @default false
   */
  elevated?: boolean
  /**
   * Icon rendered before the label. Accepts a string name (resolved via the
   * theme's `iconResolver`, defaulting to `MaterialCommunityIcons`), a
   * pre-rendered element, or a render function that receives `{ size, color }`.
   */
  leadingIcon?: IconSource
}

/**
 * Filter chip — toggleable chip used to refine or narrow content. Supports a
 * `selected` state and an optional close icon while selected.
 */
export interface FilterChipProps extends ChipCommonProps {
  variant: 'filter'
  /**
   * Whether the chip uses an elevated surface instead of an outline border.
   * @default false
   */
  elevated?: boolean
  /** Whether the chip is in a selected (toggled-on) state. */
  selected?: boolean
  /**
   * Icon rendered before the label. When the chip is selected and no
   * `leadingIcon` is provided, a checkmark is shown automatically.
   */
  leadingIcon?: IconSource
  /**
   * Callback fired when the close icon is pressed. The close icon only renders
   * when the chip is selected.
   */
  onClose?: () => void
}

/**
 * Suggestion chip — surfaces dynamic recommendations or follow-up actions
 * generated by the system.
 */
export interface SuggestionChipProps extends ChipCommonProps {
  variant: 'suggestion'
  /**
   * Whether the chip uses an elevated surface instead of an outline border.
   * @default false
   */
  elevated?: boolean
  /** Icon rendered before the label. */
  leadingIcon?: IconSource
}

/**
 * Input chip — represents a discrete piece of user-entered information such as
 * a tag or contact. Always outlined; supports either a custom `avatar` or a
 * `leadingIcon` (mutually exclusive), plus an optional close icon.
 */
export type InputChipProps = ChipCommonProps & {
  variant: 'input'
  /**
   * Callback fired when the close/remove icon is pressed. When provided,
   * renders a trailing close icon.
   */
  onClose?: () => void
} & (
    | {
        /** Custom avatar content (e.g. a small Image or View) before the label. */
        avatar: ReactNode
        leadingIcon?: never
      }
    | {
        avatar?: never
        /** Icon rendered before the label. */
        leadingIcon?: IconSource
      }
  )

/**
 * Discriminated union of chip props by `variant`. Each variant exposes only the
 * props that are meaningful for it — for example, `selected` is filter-only,
 * `elevated` is unavailable on `input`, and `avatar`/`leadingIcon` are mutually
 * exclusive on `input`.
 */
export type ChipProps =
  | AssistChipProps
  | FilterChipProps
  | SuggestionChipProps
  | InputChipProps
