import { defaultTopAppBarTokens } from './topAppBar'
import type { Theme } from './types'
import { defaultTypography } from './typography'

export const darkTheme: Theme = {
  colors: {
    primary: '#D0BCFF',
    onPrimary: '#381E72',
    primaryContainer: '#4F378B',
    onPrimaryContainer: '#EADDFF',
    primaryFixed: '#EADDFF',
    onPrimaryFixed: '#21005D',
    primaryFixedDim: '#D0BCFF',
    onPrimaryFixedVariant: '#4F378B',
    secondary: '#CCC2DC',
    onSecondary: '#332D41',
    secondaryContainer: '#4A4458',
    onSecondaryContainer: '#E8DEF8',
    secondaryFixed: '#E8DEF8',
    onSecondaryFixed: '#1D192B',
    secondaryFixedDim: '#CCC2DC',
    onSecondaryFixedVariant: '#4A4458',
    tertiary: '#EFB8C8',
    onTertiary: '#492532',
    tertiaryContainer: '#633B48',
    onTertiaryContainer: '#FFD8E4',
    tertiaryFixed: '#FFD8E4',
    onTertiaryFixed: '#31111D',
    tertiaryFixedDim: '#EFB8C8',
    onTertiaryFixedVariant: '#633B48',
    error: '#F2B8B5',
    onError: '#601410',
    errorContainer: '#8C1D18',
    onErrorContainer: '#F9DEDC',
    background: '#141218',
    onBackground: '#E6E0E9',
    surface: '#141218',
    surfaceDim: '#141218',
    surfaceBright: '#3B383E',
    surfaceContainerLowest: '#0F0D13',
    surfaceContainerLow: '#1D1B20',
    surfaceContainer: '#211F26',
    surfaceContainerHigh: '#2B2930',
    surfaceContainerHighest: '#36343B',
    onSurface: '#E6E0E9',
    surfaceVariant: '#49454F',
    onSurfaceVariant: '#CAC4D0',
    outline: '#938F99',
    outlineVariant: '#49454F',
    surfaceTint: '#D0BCFF',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#E6E0E9',
    inverseOnSurface: '#322F35',
    inversePrimary: '#6750A4',
  },
  typography: defaultTypography,
  shape: {
    roundness: 1,
    cornerNone: 0,
    cornerExtraSmall: 4,
    cornerSmall: 8,
    cornerMedium: 12,
    cornerLarge: 16,
    cornerExtraLarge: 28,
    cornerFull: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  topAppBar: defaultTopAppBarTokens,
  stateLayer: {
    pressedOpacity: 0.1,
    focusedOpacity: 0.1,
    hoveredOpacity: 0.08,
    draggedOpacity: 0.16,
    disabledOpacity: 0.38,
    disabledContainerOpacity: 0.12,
  },
  elevation: {
    level0: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    level1: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.16,
      shadowRadius: 2,
      elevation: 1,
    },
    level2: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    level3: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.24,
      shadowRadius: 8,
      elevation: 6,
    },
    level4: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.26,
      shadowRadius: 10,
      elevation: 8,
    },
    level5: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.28,
      shadowRadius: 12,
      elevation: 12,
    },
  },
  motion: {
    durationShort1: 50,
    durationShort2: 100,
    durationShort3: 150,
    durationShort4: 200,
    durationMedium1: 250,
    durationMedium2: 300,
    durationMedium3: 350,
    durationMedium4: 400,
    durationLong1: 450,
    durationLong2: 500,
    durationLong3: 550,
    durationLong4: 600,
    durationExtraLong1: 700,
    durationExtraLong2: 800,
    durationExtraLong3: 900,
    durationExtraLong4: 1000,
    easingLinear: 'cubic-bezier(0, 0, 1, 1)',
    easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
    easingStandardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
    easingStandardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
    easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
    easingEmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
    easingEmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
    // MD3 Expressive scheme, androidx ExpressiveMotionTokens.kt v0_14_0.
    // tension = Compose stiffness; friction = dampingRatio * 2 * sqrt(tension).
    springFastSpatial: { tension: 800, friction: 33.94, mass: 1 },
    springDefaultSpatial: { tension: 380, friction: 31.19, mass: 1 },
    springSlowSpatial: { tension: 200, friction: 22.63, mass: 1 },
    springFastEffects: { tension: 3800, friction: 123.29, mass: 1 },
    springDefaultEffects: { tension: 1600, friction: 80, mass: 1 },
    springSlowEffects: { tension: 800, friction: 56.57, mass: 1 },
  },
}
