import { defaultTopAppBarTokens } from './topAppBar'
import type { Theme } from './types'
import { defaultTypography } from './typography'

export const lightTheme: Theme = {
  colors: {
    primary: '#6750A4',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EADDFF',
    onPrimaryContainer: '#4F378B',
    primaryFixed: '#EADDFF',
    onPrimaryFixed: '#21005D',
    primaryFixedDim: '#D0BCFF',
    onPrimaryFixedVariant: '#4F378B',
    secondary: '#625B71',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E8DEF8',
    onSecondaryContainer: '#4A4458',
    secondaryFixed: '#E8DEF8',
    onSecondaryFixed: '#1D192B',
    secondaryFixedDim: '#CCC2DC',
    onSecondaryFixedVariant: '#4A4458',
    tertiary: '#7D5260',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFD8E4',
    onTertiaryContainer: '#633B48',
    tertiaryFixed: '#FFD8E4',
    onTertiaryFixed: '#31111D',
    tertiaryFixedDim: '#EFB8C8',
    onTertiaryFixedVariant: '#633B48',
    error: '#B3261E',
    onError: '#FFFFFF',
    errorContainer: '#F9DEDC',
    onErrorContainer: '#852221',
    background: '#FEF7FF',
    onBackground: '#1D1B20',
    surface: '#FEF7FF',
    surfaceDim: '#DED8E1',
    surfaceBright: '#FEF7FF',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F7F2FA',
    surfaceContainer: '#F3EDF7',
    surfaceContainerHigh: '#ECE6F0',
    surfaceContainerHighest: '#E6E0E9',
    onSurface: '#1D1B20',
    surfaceVariant: '#E7E0EC',
    onSurfaceVariant: '#49454F',
    outline: '#79747E',
    outlineVariant: '#CAC4D0',
    surfaceTint: '#6750A4',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#322F35',
    inverseOnSurface: '#F5EFF7',
    inversePrimary: '#D0BCFF',
  },
  typography: defaultTypography,
  shape: {
    roundness: 1,
    cornerNone: 0,
    cornerExtraSmall: 4,
    cornerSmall: 8,
    cornerMedium: 12,
    cornerLarge: 16,
    cornerExtraLarge: 28,
    cornerFull: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  topAppBar: defaultTopAppBarTokens,
  stateLayer: {
    pressedOpacity: 0.1,
    focusedOpacity: 0.1,
    hoveredOpacity: 0.08,
    draggedOpacity: 0.16,
    disabledOpacity: 0.38,
    disabledContainerOpacity: 0.12,
  },
  elevation: {
    level0: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    level1: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.16,
      shadowRadius: 2,
      elevation: 1,
    },
    level2: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    level3: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.24,
      shadowRadius: 8,
      elevation: 6,
    },
    level4: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.26,
      shadowRadius: 10,
      elevation: 8,
    },
    level5: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.28,
      shadowRadius: 12,
      elevation: 12,
    },
  },
  motion: {
    durationShort1: 50,
    durationShort2: 100,
    durationShort3: 150,
    durationShort4: 200,
    durationMedium1: 250,
    durationMedium2: 300,
    durationMedium3: 350,
    durationMedium4: 400,
    durationLong1: 450,
    durationLong2: 500,
    durationLong3: 550,
    durationLong4: 600,
    durationExtraLong1: 700,
    durationExtraLong2: 800,
    durationExtraLong3: 900,
    durationExtraLong4: 1000,
    easingLinear: 'cubic-bezier(0, 0, 1, 1)',
    easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
    easingStandardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
    easingStandardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
    easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
    easingEmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
    easingEmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  },
}
