import { Platform } from 'react-native'
import type { Typography } from './types'

const defaultFontFamily = Platform.select({
  android: 'Roboto',
  ios: 'System',
  web: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  default: 'System',
})

export const defaultTypography: Typography = {
  displayLarge: {
    fontFamily: defaultFontFamily,
    fontSize: 57,
    fontWeight: '400',
    lineHeight: 64,
    letterSpacing: -0.25,
  },
  displayMedium: {
    fontFamily: defaultFontFamily,
    fontSize: 45,
    fontWeight: '400',
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: defaultFontFamily,
    fontSize: 36,
    fontWeight: '400',
    lineHeight: 44,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: defaultFontFamily,
    fontSize: 32,
    fontWeight: '400',
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: defaultFontFamily,
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: defaultFontFamily,
    fontSize: 24,
    fontWeight: '400',
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: defaultFontFamily,
    fontSize: 22,
    fontWeight: '400',
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: defaultFontFamily,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  bodyLarge: {
    fontFamily: defaultFontFamily,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: defaultFontFamily,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  labelLarge: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: defaultFontFamily,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: defaultFontFamily,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  // MD3 Expressive emphasized styles — androidx TypeScaleTokens.kt v0_103.
  // Same size/line-height as the base style, weight one step heavier
  // (400→500, 500→700); displayLarge/titleMedium/bodyLarge/bodyMedium also
  // adjust tracking per the Compose tokens.
  displayLargeEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 57,
    fontWeight: '500',
    lineHeight: 64,
    letterSpacing: 0,
  },
  displayMediumEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 45,
    fontWeight: '500',
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmallEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 44,
    letterSpacing: 0,
  },
  headlineLargeEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMediumEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 28,
    fontWeight: '500',
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmallEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleLargeEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 22,
    fontWeight: '500',
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMediumEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmallEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  bodyLargeEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  bodyMediumEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmallEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  labelLargeEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMediumEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmallEmphasized: {
    fontFamily: defaultFontFamily,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    letterSpacing: 0.5,
  },
}
