import type { RootNativeConfig } from './types'

interface TransformOptions {
  config: RootNativeConfig
  componentName: string
  installedComponents: string[]
}

// Match single-line import/export: import { ... } from '...'
const SINGLE_LINE_IMPORT_REGEX =
  /((?:import|export)\s+(?:type\s+)?(?:\{[^}]*\}|\*\s+as\s+\w+|[\w,\s]+)\s+from\s+)(['"])([^'"]+)\2/g

// Match multi-line import/export: import {\n  ...\n} from '...'
const MULTI_LINE_IMPORT_REGEX =
  /((?:import|export)\s+(?:type\s+)?\{[\s\S]*?\}\s+from\s+)(['"])([^'"]+)\2/g

export function transformImports(
  source: string,
  options: TransformOptions,
): string {
  const { config, installedComponents } = options
  const componentsAlias = config.aliases.components
  const libAlias = config.aliases.lib

  function rewriteImport(
    match: string,
    prefix: string,
    quote: string,
    importPath: string,
  ): string {
    // @rootnative/utils → local barrel
    if (importPath === '@rootnative/utils') {
      return `${prefix}${quote}${libAlias}/rootnative-utils${quote}`
    }

    // @rootnative/core → keep as-is (npm package)
    if (importPath.startsWith('@rootnative/core')) {
      return match
    }

    // Shared internal files (e.g. ../internal/useStateLayer) — the installer
    // flattens them into the component's own directory
    if (importPath.startsWith('../internal/')) {
      const restOfPath = importPath.replace(/^\.\.\/internal\//, '')
      return `${prefix}${quote}./${restOfPath}${quote}`
    }

    // Relative inter-component imports (e.g. ../icon-button, ../typography)
    if (importPath.startsWith('../')) {
      const targetComponent = extractComponentName(importPath)

      if (targetComponent && installedComponents.includes(targetComponent)) {
        const restOfPath = importPath.replace(/^\.\.\//, '')
        return `${prefix}${quote}${componentsAlias}/${restOfPath}${quote}`
      }
    }

    // Same-directory imports (./styles, ./types) → keep as-is
    return match
  }

  // Apply multi-line regex first (greedy), then single-line for remaining
  let result = source.replace(MULTI_LINE_IMPORT_REGEX, rewriteImport)
  result = result.replace(SINGLE_LINE_IMPORT_REGEX, rewriteImport)

  return result
}

function extractComponentName(importPath: string): string | null {
  // ../icon-button → icon-button
  // ../icon-button/types → icon-button
  const match = importPath.match(/^\.\.\/([^/]+)/)
  return match ? match[1] : null
}

export function generateUtilsBarrel(
  utilNames: string[],
  utilExports: Record<string, string[]>,
  utilTypeExports: Record<string, string[]> = {},
): string {
  const lines = ['// Auto-generated by rootnative CLI. Do not edit.']

  for (const utilName of utilNames.sort()) {
    const exports = utilExports[utilName]
    if (exports && exports.length > 0) {
      lines.push(`export { ${exports.join(', ')} } from './${utilName}'`)
    }
    const typeExports = utilTypeExports[utilName]
    if (typeExports && typeExports.length > 0) {
      lines.push(
        `export type { ${typeExports.join(', ')} } from './${utilName}'`,
      )
    }
  }

  return lines.join('\n') + '\n'
}
